baseURL = 'https://peter-wyss.ch/'
languageCode = 'de-ch'
title = 'Peter Wyss'
theme = 'hugo-paper'
[params]
monoDarkIcon = true                       # show monochrome dark mode icon

[menu]

  [[menu.main]]
    identifier = "about"
    name = "Kontakt"
    url = "/about/"
    weight = 10

